font=JetBrainsMono Nerd Font Propo:size=13
font-bold=JetBrainsMono Nerd Font Propo:size=13:style=Bold
font-italic=JetBrainsMono Nerd Font Propo:size=13:style=Italic
line-height=24px
letter-spacing=0

[main]
shell=/usr/bin/fish
term=foot
login-shell=no
pad=20x10                             # Comfortable internal padding
initial-window-size-chars=100x25
selection-target=primary

[cursor]
style=beam
#color=f5e0dc 1e1e2e                   # Rosewater on Mocha Base
blink=yes
beam-thickness=1.1

[colors-dark]
alpha=1.00                            # Subtle transparency
foreground=cdd6f4                     # Text (Mocha Text)
background=000000                     # Base (Mocha Base)

## Normal colors
regular0=45475a                       # Surface 1
regular1=f38ba8                       # Red
regular2=a6e3a1                       # Green
regular3=f9e2af                       # Yellow
regular4=89b4fa                       # Blue
regular5=f5c2e7                       # Pink
regular6=94e2d5                       # Teal
regular7=bac2de                       # Subtext 1

## Bright colors
bright0=585b70                        # Surface 2
bright1=f38ba8                        # Red
bright2=a6e3a1                        # Green
bright3=f9e2af                        # Yellow
bright4=89b4fa                        # Blue
bright5=f5c2e7                        # Pink
bright6=94e2d5                        # Teal
bright7=a6adc8                        # Subtext 0

[scrollback]
lines=5000
multiplier=4.0

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=always

[mouse]
hide-when-typing=yes
