# Preload the image into RAM (faster switching)
preload = ~/Downloads/ArchInstall/city-skyline.jpg

# Set the wallpaper for all monitors (empty monitor name before the comma)
wallpaper = Virtual-1,~/Downloads/ArchInstall/city-skyline.jpg

# Disable the "Hyprland" splash text
splash = false
