general {
    # The command to lock the screen
    lock_cmd = pidof hyprlock || hyprlock

    # Lock the screen before the system goes to sleep
    before_sleep_cmd = loginctl lock-session

    # Turn the display back on after waking up
    after_sleep_cmd = niri msg action power-on-monitors
}

# 1. Dim the screen (after 2.5 minutes)
listener {
    timeout = 45
    on-timeout = brightnessctl set 20% -q         # Lowers brightness
    on-resume = brightnessctl set 100% -q        # Restores brightness
}

listener {
    timeout = 90
    on-timeout = brightnessctl set 10% -q         # Lowers brightness
    on-resume = brightnessctl set 100% -q        # Restores brightness
}

# 2. Lock the screen (after 5 minutes)
listener {
    timeout = 180
    on-timeout = loginctl lock-session            # Triggers hyprlock
}

# 3. Turn off display (after 5.5 minutes)
listener {
    timeout = 120
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# 4. Suspend the laptop (after 10 minutes)
listener {
    timeout = 1800
    on-timeo ut = systemctl suspend
}
