[mgr]
ratio          = [1, 3, 4]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true
linemode       = "size"

[preview]
tab_size        = 2
max_width       = 1000
max_height      = 1000
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75

[opener]
edit = [
    { run = 'micro "$@"', block = true, desc = "micro", for = "unix" }
]
open = [
    { run = 'xdg-open "$@"', desc = "Open", for = "unix" }
]

[open]
prepend_rules = [
    { url = "*.txt",  use = "edit" },
    { url = "*.json", use = "edit" },
    { url = "*.kdl",  use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "open" },
    { mime = "video/*", use = "open" }
]
